import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{ children: React.ReactNode; }>) {
    return (
    <ClerkProvider>
        <html lang="en">

        <body>
            <SidebarProvider>
                <AppSidebar />
                <main className="w-full px-12 py-5">
                    <div className="flex justify-between w-full mb-6">
                        <SidebarTrigger />
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                        <SignedOut>
                            <SignInButton>
                                <Button className="px-3 py-2 bg-gray-400 rounded-full text-white">Sign in</Button>
                            </SignInButton>
                        </SignedOut>
                    </div>
                    {children}

                </main>
            </SidebarProvider>
        </body>

        </html>
    </ClerkProvider>
    );
    }
